### ISSUE TITLE
Support python 3.8

### ISSUE THREAD

**Issue by chandlernine** [SoftwareAG/nyoka#38]
Hello maintainers,

The following line in versions 4.2.0 and 4.2.1 prevents me from using python 3.8:

https://github.com/nyoka-pmml/nyoka/blob/4.2.1/setup.py#L32

I'd appreciate it if you'd relax the constraint or document why there is this constraint.

**Comment by nyoka-pmml** [comment]
Hi @chandlernine, this constraint will be removed in our next release.

**Comment by Nirmal-Neel** [comment]
Hi @chandlernine, the constraint is removed in the release of version 4.3.0. See the [Release Notes](https://github.com/SoftwareAG/nyoka/releases/tag/4.3.0)
