### ISSUE TITLE
 unexpected element: DeepNetwork

### ISSUE THREAD

**Issue by AbdealiJK** [SoftwareAG/nyoka#40]
Hi, I was trying to use a PMML I generated using nyoka from tensorflow using jpmml-evaluator.
I got the error:
```
unexpected element (uri:"http://www.dmg.org/PMML-4_4", local:"DeepNetwork").
Expected elements are
  <{http://www.dmg.org/PMML-4_4}TreeModel>,
  <{http://www.dmg.org/PMML-4_4}Extension>,
  <{http://www.dmg.org/PMML-4_4}MiningModel>,
  <{http://www.dmg.org/PMML-4_4}Header>,
  <{http://www.dmg.org/PMML-4_4}BayesianNetworkModel>,
  <{http://www.dmg.org/PMML-4_4}GaussianProcessModel>,
  <{http://www.dmg.org/PMML-4_4}GeneralRegressionModel>,
  <{http://www.dmg.org/PMML-4_4}BaselineModel>,
  <{http://www.dmg.org/PMML-4_4}Scorecard>,
  <{http://www.dmg.org/PMML-4_4}SupportVectorMachineModel>,
  <{http://www.dmg.org/PMML-4_4}ClusteringModel>,
  <{http://www.dmg.org/PMML-4_4}AssociationModel>,
  <{http://www.dmg.org/PMML-4_4}RuleSetModel>,
  <{http://www.dmg.org/PMML-4_4}SequenceModel>,
  <{http://www.dmg.org/PMML-4_4}MiningBuildTask>,
  <{http://www.dmg.org/PMML-4_4}NearestNeighborModel>,
  <{http://www.dmg.org/PMML-4_4}TextModel>,
  <{http://www.dmg.org/PMML-4_4}TransformationDictionary>,
  <{http://www.dmg.org/PMML-4_4}AnomalyDetectionModel>,
  <{http://www.dmg.org/PMML-4_4}NaiveBayesModel>,
  <{http://www.dmg.org/PMML-4_4}TimeSeriesModel>,
  <{http://www.dmg.org/PMML-4_4}DataDictionary>,
  <{http://www.dmg.org/PMML-4_4}NeuralNetwork>,
  <{http://www.dmg.org/PMML-4_4}RegressionModel> javax.xml.bind.UnmarshalException
```

On manual inspection, I see that in the PMML, there is an element called `DeepNetwork`.

On looking at the jpmml PMML 4.4 XSD: https://github.com/jpmml/pmml-xsd/blob/master/xsd/pmml-4-4.xsd#L384
There was only `NeuralNetwork` and no `DeepNetwork`.

But I see it is present in the Nyoka PMML 4.4 XSD: https://github.com/SoftwareAG/nyoka/blob/master/nyoka/pmml44.xsd#L797

Also, in the DMG documentation - http://dmg.org/pmml/v4-4/GeneralStructure.html
I could not find a `DeepNetwork` node

I couldn't figure out if `DeepNetwork` a standard PMML node ? Or something very specific to Nyoka ?
How do I run and evaluate nyoka PMML files ?

**Comment by Nirmal-Neel** [comment]
Hi @AbdealiJK, please refer to #23

**Comment by AbdealiJK** [comment]
Thanks @Nirmal-Neel - I should have searched a bit more
