### ISSUE TITLE
SARIMAX exporter creates invalid PMML file

### ISSUE THREAD

**Issue by alenhrga** [SoftwareAG/nyoka#42]
I exported my SARIMAX model with latest Nyoka release (v4.3.0) and the resulting PMML file is created accordant to schema version 4.4. Exported PMML file  had `<InterceptVector>` attribute which is not defined in schema version 4.4.

Part of the exported PMML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<PMML xmlns="http://www.dmg.org/PMML-4_4" version="4.4">
    <Header copyright="Copyright (c) 2018 Software AG" description="State Space Model">
        <Application name="Nyoka" version="4.3.0"/>
        <Timestamp>2020-10-06 11:47:06.546081</Timestamp>
    </Header>
    <DataDictionary numberOfFields="2">
        <DataField name="SpotPriceEUR" optype="continuous" dataType="double"/>
        <DataField name="h" optype="continuous" dataType="integer"/>
    </DataDictionary>
...
...
    <MeasurementMatrix>
                <Matrix nbRows="1" nbCols="49">
                    <Array type="real">...</Array>
                </Matrix>
    </MeasurementMatrix>
    <InterceptVector>
        <Array n="49" type="real">...</Array>
     </InterceptVector>
        </StateSpaceModel>
    </TimeSeriesModel>
</PMML>
```

[PMML 4.4 specification](http://dmg.org/pmml/v4-4/pmml-4-4.xsd) **does not have** `<InterceptVector>` attribute defined so this PMML file is actually invalid.
According to PMML spec, `<InterceptVector>` attribute is defined in PMML version [4.4.1](http://dmg.org/pmml/v4-4-1/pmml-4-4.xsd)

**Comment by Nirmal-Neel** [comment]
Hi @alenhrga, Nyoka 4.3.0 is using an intermediate schema which lies between PMML schema 4.4 and 4.4.1. Now, as PMML schema 4.4.1 is out there, Nyoka will also be updated with the new schema which is already in progress. Thanks!

**Comment by Nirmal-Neel** [comment]
Hi @alenhrga, Nyoka 4.4.0 has support for PMML schema 4.4.1. Check [Release notes 4.4.0](https://github.com/SoftwareAG/nyoka/releases/tag/4.4.0)
