### ISSUE TITLE
Support for OrdinalEncoder from sklearn

### ISSUE THREAD

**Issue by victornoel** [SoftwareAG/nyoka#45]
Hi,

I noticed you support most of the available encoders from sklearn, but not OrdinalEncoder. Is there any plan to support it?

Thanks!

**Comment by victornoel** [comment]
@Nirmal-Neel hi, any idea about this? Or maybe some guidance on how to implement it? Cheers

**Comment by Nirmal-Neel** [comment]
Hi @victornoel, sorry for the late reply. Yes, we have plan to support few more models/encoders/transformers from scikit-learn. But the timeline is not clear yet.

**Comment by Nirmal-Neel** [comment]
> @Nirmal-Neel hi, any idea about this? Or maybe some guidance on how to implement it? Cheers

If you want to implement it, then you could go through [Transformation Dictionary and Derived Fields](http://dmg.org/pmml/v4-4-1/Transformations.html) and could find an `EXPRESSION` which fits well with OrdinalEncoder. Then you could follow [pre_process.py](https://github.com/SoftwareAG/nyoka/blob/master/nyoka/skl/pre_process.py#L157) and add the code for generating those elements.

**Comment by Nirmal-Neel** [comment]
Hi @victornoel, did that answer your question?

**Comment by victornoel** [comment]
@Nirmal-Neel ah yes, sorry for not getting back to you.

It does indeed, I'm still exploring various possibilities in converting my pipelines to PMML, e.g., I could also rethink my preprocessing to avoid using this encoder. I'm not moving at very high pace with this endeavour ^^
But if I need it, I will try to implement and contribute support for `OrdinalEncoder` to nyoka!

Until then I guess we can keep this ticket open, correct? If not, feel free to close it, no problem with me :)

**Comment by qianjiangchao1992** [comment]
hello，I want to customize a pipeline through the DataFrameMapper, but I see that pre_process enforces the type, or is it possible to provide a similar interface to increase flexibility

**Comment by qianjiangchao1992** [comment]
@victornoel hello，I want to customize a pipeline through the DataFrameMapper, but I see that pre_process enforces the type, or is it possible to provide a similar interface to increase flexibility

**Comment by victornoel** [comment]
@qianjiangchao1992 I am sorry, I have no idea. I'm not sure here is the right place to ask though...

**Comment by qianjiangchao1992** [comment]
ok,thanks

**Comment by mohammedfazil003** [comment]
Since it's more than a year now, closing the ticket.
Thanks
