### ISSUE TITLE
 the following pipeline is valid, but skl_to_pmml fails with a traceback error:

### ISSUE THREAD

**Issue by hsx1612727380** [SoftwareAG/nyoka#52]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/3p/nkzqwh_177jgrfhcl035m1l80000gp/T/ipykernel_57171/2423173579.py in <module>
      7 
      8 
----> 9 xgboost_to_pmml(pipeline, features, target_name, "/Users/huangshouxi/IdeaProjects/grocery/groceryqa-tools-predict/groceryqa-tools-predict-service/src/main/resources/model/xgb-pick.pmml")

~/opt/anaconda3/lib/python3.9/site-packages/nyoka/xgboost/xgboost_to_pmml.py in xgboost_to_pmml(pipeline, col_names, target_name, pmml_f_name, model_name, description)
     74             categoric_values = pml_pp['categorical_feat_values']
     75             mining_imp_val = pml_pp['mining_imp_values']
---> 76         PMML_kwargs = get_PMML_kwargs(model,
     77                                       derived_col_names,
     78                                       col_names,

~/opt/anaconda3/lib/python3.9/site-packages/nyoka/xgboost/xgboost_to_pmml.py in get_PMML_kwargs(model, derived_col_names, col_names, target_name, mining_imp_val, categoric_values, model_name)
    116         Get the PMML model argument based on XGBoost model object
    117     """
--> 118     algo_kwargs = {'MiningModel': get_ensemble_models(model,
    119                                                       derived_col_names,
    120                                                       col_names,

~/opt/anaconda3/lib/python3.9/site-packages/nyoka/xgboost/xgboost_to_pmml.py in get_ensemble_models(model, derived_col_names, col_names, target_name, mining_imp_val, categoric_values, model_name)
    153     model_kwargs = sklToPmml.get_model_kwargs(model, col_names, target_name, mining_imp_val, categoric_values)
    154     if 'XGBRegressor' in str(model.__class__):
--> 155         model_kwargs['Targets'] = sklToPmml.get_targets(model, target_name)
    156     mining_models = list()
    157     mining_models.append(pml.MiningModel(

~/opt/anaconda3/lib/python3.9/site-packages/nyoka/skl/skl_to_pmml.py in get_targets(model, target_name)
   1094                 pml.Target(
   1095                     field=target_name,
-> 1096                     rescaleConstant="{:.16f}".format(model.base_score)
   1097 		)
   1098             ]

TypeError: unsupported format string passed to NoneType.__format__

**Comment by hsx1612727380** [comment]
![image](https://user-images.githubusercontent.com/14011324/149339606-6affa365-787c-4407-8dba-70530db5010b.png)

**Comment by hsx1612727380** [comment]
@vinayvinkumar 3_xgboost_With_PreProcess .ipynb made the same mistake

**Comment by Nirmal-Neel** [comment]
Hi @hsx1612727380, which version of xgboost are you using?

**Comment by hsx1612727380** [comment]
'1.5.0'

**Comment by hsx1612727380** [comment]
> Hi @hsx1612727380, which version of xgboost are you using?

'1.5.0'

**Comment by Nirmal-Neel** [comment]
Currently, our exporter does not support xgboost with version >= 1.0. We are working on it and soon we will provide a release with that support.

**Comment by Nirmal-Neel** [comment]
The list of supported libraries and versions are mentioned here - https://github.com/SoftwareAG/nyoka#list-of-libraries-and-models-supported-by-nyoka-

**Comment by hsx1612727380** [comment]
> The list of supported libraries and versions are mentioned here - https://github.com/SoftwareAG/nyoka#list-of-libraries-and-models-supported-by-nyoka-

Thanks

**Comment by Nirmal-Neel** [comment]
Hi @hsx1612727380, nyoka release [5.2.0](https://github.com/SoftwareAG/nyoka/releases/tag/5.2.0) adds support for xgboost 1.x.x.
