### ISSUE TITLE
Does the xgboost implementation support categorical features?

### ISSUE THREAD

**Issue by zigs824** [SoftwareAG/nyoka#55]
The previous issue mentioned lgbm does not, I haven't seen any xgboost examples using categorical transformers. I am trying to use onehotencoder for my project because I saw it was listed as supported. Thanks!

**Comment by Nirmal-Neel** [comment]
Hi @zigs824, we handle each transformer/estimator in a pipeline independently. OneHotEncoder is a transformer which our tool supports and similarly xgboost. Does this answer your question?

**Comment by mohammedfazil003** [comment]
Hello @zigs824 ,
Does it address your query regarding Xgboost, if so can we close the ticket.
Thanks.

**Comment by zigs824** [comment]
> 

Hi, yes please close it. Thanks!
