### ISSUE TITLE
The readme still contains Keras, which is no longer supported

### ISSUE THREAD

**Issue by AayushSameerShah** [SoftwareAG/nyoka#58]
## The Problem
I am glad, I came to this repository finding for the Keras → PMML exporter. But the new version seems not to be supporting the `Keras2pmml`. But the mention of Keras is still there *(yes in the current version)*.

I tried to go back to multiple versions and finally found that Nyoka has stopped supporting Keras export since version 5.0.0. Hence the last supporting version is 4.4.0.

## The solution
So, to make better usability, you should mention in the current readme that "We have stopped Keras support & to use that please consider downloading the 4.4.0 release" .

There, again we will need to face the dependencies of Keras x TF x Nyoka. Thus, I have found the following configurations for anyone who is looking for keras2pmml and came here.

## More 
**Keras**: 2.2.4
**TF**: 1.13.1
**Nyoka**: 4.4.0

Consider it installing on Google Colab or something, because the older versions of Keras and TF don't support new python. They expect python 3.6, 3.7 etc. So... try accordingly.

**Comment by mohammedfazil003** [comment]
Hello @AayushSameerShah,

Thank you for your valuable time and mentioning about it. 
The readme file is updated in the following comit: https://github.com/SoftwareAG/nyoka/commit/0214a0b44db2c107380e256d998ec1aac75d8704
