### ISSUE TITLE
How can I write the fit_transform pipeline 

### ISSUE THREAD

**Issue by qianjiangchao1992** [SoftwareAG/nyoka#60]
hello，I want to customize a pipeline through the DataFrameMapper, but I see that pre_process enforces the type, or is it possible to provide a similar interface to increase flexibility

**Comment by mohammedfazil003** [comment]
Hi @qianjiangchao1992, 
Currently we don't have support for customize pipeline in Nyoka. We do have this as a part of future backlog.
Thanks.
